README.md
dockerspawner/systemuserspawner.py

This should mean that the user_ids don't need to be stored ahead of time.
- remove user_ids dict
- only store single user_id on each Spawner
- load user_id from database state (allows Authenticator to set it)
- get default user_id from pwd, if not in db

remove SystemUserSpawner.user_ids

---

dockerspawner/dockerspawner.py

This makes it possible to connect to the docker daemon using TLS authentication, which is necessary (for example) if the docker container being launched is being created on a different machine.

Add support for TLS authentication

---

dockerspawner/dockerspawner.py

One of my containers died violently on startup and docker started returning an empty string for a status.  Not sure yet what causes this, but throwing an explicit error here is more useful than an `IndexError`, which was the previous behavior.

DEV: Barf more usefully on empty string for docker status.

---

dockerspawner/dockerspawner.py

Adds the `remove_containers` config option, which is `False` by default, but if `True` will cause containers to be removed after they're stopped.

Allow option to remove containers after they're stopped

---

dockerspawner/dockerspawner.py
dockerspawner/systemuserspawner.py

Support both create_container and start optional args. Made args configurable, so you do not have to extend DockerSpawner to just change the args.

Docker args config

---

dockerspawner/dockerspawner.py

This is useful when the IP the hub is bound on is not directly reachable by the containers.  When the config option is not set, `Hub.ip` is used.

Allow specifying Hub IP for containers to communicate.

---

dockerspawner/dockerspawner.py

now that passing host_config parameters to start is deprecated.  (https://github.com/docker/docker-py/commit/329662c53ed13254449ef55742d2e8d577e0dd97)
For #33.
This also fixes usage of mem_limit and memswap_limit in our internal repo.
cc: @minrk @ssanderson

Use host_config in create_container

---

dockerspawner/dockerspawner.py
dockerspawner/systemuserspawner.py

jupyter/jupyterhub#261 removes the dependency on IPython.utils.traitlets. This PR uses the standalone traitlets directly.

Use standalone traitlets

---

dockerspawner/dockerspawner.py
requirements.txt

only allow `[A-Za-z0-9_-]`, escape everything else.
cf [docker container name spec](https://github.com/ajhager/docker/commit/f63cdf0260cf6287d28a589a79d3f947def6a569)
closes #25
closes #39

escape username in container name

---

dockerspawner/dockerspawner.py

When using TLS, sometimes the certs don't exactly match the hostname where the docker daemon is running. For example, the cert might be for `*` but docker-py will complain if `assert_hostname` is true (which is the default) because `*` is not the same as the actual hostname.
I don't think the docker command line client actually does this assertion, because accessing the docker daemon via the command line with TLS works fine, it's just through docker-py that it doesn't by default (but it does when the assertion is disabled).

Add option to toggle hostname assertion with TLS

---

dockerspawner/dockerspawner.py

I was not able able to make dockerspawner work with boot2docker without hardcoding dockerspawner code.
Here is an added option that tells `DockerSpawner` to use [`docker.utils.kwargs_from_env`](https://docker-py.readthedocs.org/en/latest/boot2docker/) to build the docker client.

Add a use_docker_client_env option

---

dockerspawner/dockerspawner.py

according to [urllib3] (https://urllib3.readthedocs.org/en/latest/pools.html#urllib3.connectionpool.HTTPSConnectionPool):  "VerifiedHTTPSConnection uses one of assert_fingerprint, assert_hostname and host in this order to verify connections. If assert_hostname is False, no verification is done."
With the current default value of `True`, I get an AttributeError when urllib3 tries to call `lower` on `True` in order to compare it to another string:
```
File "/Users/rich/.virtualenvs/research_env/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 253, in connect
match_hostname(cert, self.assert_hostname or hostname)
File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 268, in match_hostname
if …
```

MAINT: tls_assert_hostname should be either a string or False

---

examples/oauth/README.md
examples/oauth/run.sh

Example is from when oauthenticator was a single file, not an installable package.
cc @RafalSkolasinski

install oauthenticator in oauth example

---

singleuser/Dockerfile
singleuser/README.md
systemuser/Dockerfile
systemuser/README.md

instead of deprecated ipython/scipystack
closes #55

use jupyter/scipy-notebook as single-user base image

---

dockerspawner/dockerspawner.py

This allows us to give each docker instance a different 'home' 
somewhere on shared storage on the host, thus making it persistant.

Allow use of usernames in volume paths

---

dockerspawner/dockerspawner.py

The context for this proposed change is, that I want to be able to use internal docker IP addresses instead of the public ones. I am running the jupyterhub server (as docker container) and the user containers on the same docker engine which is enough for smaller scenarios without a swarm. If I use the code as it is the public ip/port  of the spawned user container is used (localhost and random unprivileged port). These changes add the possibility to use the internal IP instead and (since it is not required in that case) do not expose a port to the outside.

Allow usage of internal docker subnet IP

---

dockerspawner/dockerspawner.py

As announced in my UseInternalIP pull request, this is the change necessary for docker 1.9 networks. It allows you to have dockerized jupyterhub and the containers in a non-standard docker network. In my use case I want to restrict the access of jupyterhub containers (non-jupyterhub related) to other docker containers in the same deployment. Just a simple security measure.

Allow usage of custom docker networks with internal ip

---

singleuser/Dockerfile
singleuser/singleuser.sh
systemuser/Dockerfile
systemuser/systemuser.sh

- get jupyterhub-singleuser script from its new home
- smoke test entrypoints to ensure they can at least produce help output
- base system user image on singleuser to reduce duplication

more dockerfile updates

---

dockerspawner/dockerspawner.py

Rather than use `container_ip` from the DockerSpawner configuration, use the IP address reported by the `docker port` command. This should behave identically when `container_ip` is left at its default or specified explicitly, because Docker will report the IP that was bound. But, by using `container_ip` as the interface to bind and reading the read address from Docker after container launch, users can specify:
```python
c.DockerSpawner.container_ip = "0.0.0.0"
```
And JupyterHub will connect to the launched container at its public IP.
With only this change, I was able to use the regular `DockerSpawner` to run JupyterHub on Swarm, with user containers launching on different nodes. :confetti_ball:

Use HostIp from docker port output

---

dockerspawner/dockerspawner.py

To address:
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Container jupyter-USER running on unhealthy node NODE'")

Forget container id if node is unhealthy

---

dockerspawner/dockerspawner.py

This is likely caused by failure to properly start the container
better error message for #71, though doesn't fix whatever the root cause may have been.

better error when no port can be retrieved

---

dockerspawner/dockerspawner.py

Is there a particular reason why `yield from` was changed to `yield` in a535b08? With the latest master, I get the following error when I use dockerspawner with Swarm.
```
[E 2016-02-23 01:53:43.647 JupyterHub web:1524] Uncaught exception GET /hub/user/EdwardJKim (192.168.0.10)
HTTPServerRequest(protocol='http', host='129.114.110.10', method='GET', uri='/hub/user/EdwardJKim', version='HTTP/1.1', remote_ip='192.168.0.10', headers={'X-Forwarded-Host': '129.114.110.10', 'Remote-User': '(null)', 'Accept-Language': 'en-US,en;q=0.8,ko;q=0.6', 'X-Forwarded-For': '192.241.58.150,192.168.0.10', 'Host': '129.114.110.10', 'Referer': 'https://129.114.110.10/hub/home', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', …
```

revert to "yeild from" to work with swarm

---

systemuser/systemuser.sh

If the user exists and DockerSpawner.remove_containers is not set, this script will exit immediately (-e) and the user's container won't start. data-8 is running into this. Also described at https://github.com/jupyter/dockerspawner/issues/67#issuecomment-179557330.

Skip useradd if the user exists

---

dockerspawner/dockerspawner.py
singleuser/singleuser.sh
systemuser/systemuser.sh

Following my conversation with @minrk, i added the `--notebook-dir` flag to the spawning bash script with a little bash magic for optionally applying it.

Added support for specifying notebook_dir of spawned container

---

dockerspawner/systemuserspawner.py

This will match the DockerSpawner parent class and prevent an AttributeError since _env_default is no longer defined in the parent since PR #84.
```
File "/opt/conda/lib/python3.5/site-packages/dockerspawner/systemuserspawner.py", line 102, in _env_default
env = super(SystemUserSpawner, self)._env_default()
AttributeError: 'super' object has no attribute '_env_default'
```

Extend get_env instead of _env_default in systemuserspawner.py.

---

dockerspawner/dockerspawner.py

Adds the container_port traitlet and removes the hardcoded entries.

Adding container_port option to bind against a different port than the default (8888)

---

dockerspawner/dockerspawner.py
tests/volumes_test.py

Red Hat uses SELinux enforcing. You need to modify the SELinux context globally, or more
narrowly [add a volume label (`:Z`) to volume binds](https://docs.docker.com/engine/userguide/containers/dockervolumes/#volume-labels). docker-py does allow an arbitrary `mode` on the binds. However, you cannot specify both `ro` and `mode`.
This PR allows the following configuration for volumes:
```python
c.DockerSpawner.volumes = {
'/nfs/{username}': {'bind': '/home/{username}', 'mode': 'Z'}
'/other/dir': '/old/style',
}
```
In addition, this PR fixes the following issues:
1) volume_binds was formatting username on the mount_points, but volume_mount_points was not.
2) volume_mount_points should be sorted, because you might be mounting one point on another.
There's a unit test for the new code. It …

Allow SELinux volume label on volumes

---

dockerspawner/dockerspawner.py

While this might be obvious to some, it took me quite a while to figure out how to do what I wanted to do. You could also use an [empty yield after the return](http://stackoverflow.com/a/13243870/3075806), but `async` is the better solution for Python 3.
I wanted to add the ability to set "network_name = host", but that's much more involved, and jupyterhub/jupyterhub#587 seems to be preferable.

document overriding get_ip_and_port for network_mode=host

---

dockerspawner/dockerspawner.py

rather than a single asyncio-style method in a class full of tornado-async code.

make get_ip_and_port a tornado coroutine

---

README.md

There's no reason it is useful only for 'basic, temporary' servers.

Clarify language around use of DockerSpawner

---

examples/oauth/jupyterhub_config.py
requirements.txt

juypter_client should now be used instead of ipython.utils; also adding it to the requirements

Change legacy IPython code to jupyter_client

---

systemuser/Dockerfile

This commit removes the jovyan home directory from the systemuser dockerfile. This makes it such that if a user in the container does `ls /home` they only see their home directory.
The work directory must be changed in order for the docker build command to successfully remove the folder, so the work directory was changed from `/home/jovyan/work` to just `/home`

Remove jovyan home directory from systemuser image

---

dockerspawner/dockerspawner.py
dockerspawner/systemuserspawner.py

JupyterHub 0.7 will enable returning ip, port, rather than relying on start editing db state.

return ip, port from start

---

.travis.yml
dev-requirements.txt
dockerspawner/dockerspawner.py
tests/volumes_test.py

Added and tested code as suggested in Issue #90 discussion. Found additional issue with usernames that cannot be used as filenames when inserting them into volume labels. I added slugify code from Django framework to normalize usernames so they can be filenames.

Fixes Issue #90 and added code to normalize username substitution

---

dockerspawner/dockerspawner.py
tests/volumes_test.py

it was scrubbing valid identifiers.
- non-ascii characters should be allowed in paths
- spaces should not occur in usernames, but they are valid in files, anyway
- unicode normalizing probably shouldn't occur, either
@whitead do you have any examples of the usernames that prompted slugify?

revert slugify

---

CONTRIBUTING.md
README.md
singleuser/README.md

The README is a bit light on details of DockerSpawner vs. SystemSpawner. Which to use? Why?

Improve README to better explain both spawners

---

dockerspawner/dockerspawner.py

prevents JupyterHub 0.7.1 from deleting our API tokens while we are still using them
counterpart to https://github.com/jupyterhub/jupyterhub/pull/910

indicate that we will resume if not using remove_containers

---

dockerspawner/systemuserspawner.py

The start method in SystemUserSpawner did not accept the same arguments as
the start mehtod in DockerSpawner. This made subclassing SystemUserSpawner
difficult as passing arguments was not possible.
This commit changes the arguments of start to match those of the
DockerSpawner method. It also modified the call to the super, passing in the
added arguments.
This commit does change the functionality a bit, as `working_dir` is no
longer forced to be `start.homedir` and can be overwritten.

Modified arguments to start in SystemUserSpawner

---

dockerspawner/dockerspawner.py

This came up when I was doing [these swarm experiments](https://github.com/minrk/jupyterhub-swarm/blob/master/hub-inside/jupyterhub_config.py#L20), where I discovered that to tell DockerSpawner to listen internally on a docker network required three separate config options:
1. network_name (the name of the network when retrieving the ip)
2. use_internal_ip (whether to lookup internal connection info at all)
3. `host_config.network_mode` (tell the container to run on the given network)
I've updated it so that setting `network_name` signals that docker networking is in use and internal connections should be used. So what was:
```python
c.DockerSpawner.network_name = 'jupyterhub'
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.extra_host_config = {
'network_mode': 'jupyterhub',
}
``` …

use internal ip connections when setting network name

---

dockerspawner/dockerspawner.py

avoids need to add extra config when using known images that we control

use `start-singleuser` entrypoint by default with Jupyter docker stacks

---

dockerspawner/dockerspawner.py

This fixes a problem where docker-py is returning a string for the port for the following configuration:
```
$ docker --version
Docker version 17.05.0-ce, build 89658be
$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> docker.__version__
'2.2.1'
```
however the call to the docker module actually generates the following, which make be the underlying issue:
```
[I 2017-06-02 20:07:41.727 JupyterHub dockerspawner:498] Bad message (TypeError('not all arguments converted during string formatting',)): {'args'
: ([{'HostIp': '127.0.0.1', 'HostPort': '10245'}],), 'levelname': 'INFO', 'funcName': 'get_ip_and_port', 'thread': 140445252167424, 'module': 'doc
kerspawner', …
```

force conversion of port to int

---

dockerspawner/systemuserspawner.py

Remove module-level coupling to `pwd` which isn't available on Windows.
cf. jupyterhub/jupyterhub#1224

Windows fix

---

dockerspawner/dockerspawner.py

docker-stacks properly launch singleuser when JUPYTERHUB_API_TOKEN is defined.

remove special-case entrypoint for docker-stacks

---

dockerspawner/dockerspawner.py

In some cases, it is needed to override the docker API client version. For example, we can get error messages with an outdated Swarm cluster, like this :
docker.errors.APIError: 400 Client Error: Bad Request ("b'your client is too new (API version 1.27). The newest supported API version is 1.26.0'")
This modification keeps the default behavior, but allows to override the version via client_kwargs if necessary

Allow override of docker client api version

---

dockerspawner/dockerspawner.py
singleuser/Dockerfile
singleuser/hooks/build
singleuser/hooks/post_push
singleuser/install_jupyterhub

generates jupyterhub/singleuser:0.7 and jupyterhub/singleuser:0.8
and picks these by default, so that the default behavior of DockerSpawner is to launch with an image that works.
Following tags are created: 0.7 (aliases: 0.7.2, latest), master (aliases: 0.8)

tag images with JupyterHub version on DockerHub

---

dockerspawner/dockerspawner.py

docker docs clearly state that HostPort is a string. I'm not sure if/when this changed, or if that code path was just rarely used.

Remove warning about casting port from str

---

dockerspawner/dockerspawner.py

JPY_API_TOKEN env is deprecated (but still present)

handle JUPYTERHUB_API_TOKEN when looking for tokens

---

dockerspawner/dockerspawner.py

ensures that a failed start or previous `.remove_containers = False` run doesn't bleed into the next start
closes #182

remove container on start if self.remove_containers

---

dockerspawner/dockerspawner.py

removes assumption that image has `EXPOSE port` line

ensure internal port is exposed

---

dockerspawner/dockerspawner.py

After patching my jupyterhub to work I next ran into this error:
```python-traceback
Traceback (most recent call last):
File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\web.py", line 1511, in _execute
result = yield result
File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1055, in run
value = future.result()
File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "C:\Miniconda3\envs\jupyterhub\lib\site-packages\tornado\gen.py", line 1069, in run
yielded = self.gen.send(value)
File "c:\dev\src\jupyterhub\jupyterhub\handlers\login.py", line 87, in post
if user.spawner:
File "c:\dev\src\jupyterhub\jupyterhub\user.py", line 224, in __getattr__
return …
```

Fix deprecation warning

---

dockerspawner/dockerspawner.py

Hi,
this is a little modification to allow a per user, per docker-image container name (needed when using profilespawner):
Because i want user to have multiple docker container instances with differents docker images, i added the "user_container_name" option (by default "{username}-{imagename}"), and remove "container_prefix" which is no longer needed (because "user_container_name" can be "prefix-{username}-{imagename}-suffix")
For instance, i use profilespawner and user can select "jupyterhub/systemuser", or "jupyter/r-notebook" docker image:
With this patch the user "bob" have 2 docker containers:
bob-jupyterhub_systemuser and bob-jupyter_r-notebook. No need to remove a container to use other image.

Add container_name_template config

---

dockerspawner/dockerspawner.py

Passing kwargs to start now raises an exception in docker-py
Closes #192

Remove deprecated extra_start_kwargs

---

.gitignore
README.md
dockerspawner/__init__.py
dockerspawner/swarmspawner.py

Added a new class called Swarmspawner by duplicating Dockerspawner and modifying it where needed. Removed deprecated fields instead of adapting them. [My working sample hub config looks like the following](https://github.com/scnerd/pythonathon_docker/blob/master/jupyterhub/jupyterhub_config.py):
```python
c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.spawner_class = 'dockerspawner.SwarmSpawner'
c.SwarmSpawner.image = os.environ.get('DOCKER_NOTEBOOK_IMAGE')
c.SwarmSpawner.use_docker_client_env = True
network_name = os.environ['DOCKER_NETWORK_NAME']
c.SwarmSpawner.use_internal_ip = True
c.SwarmSpawner.network_name = network_name
c.SwarmSpawner.extra_host_config = {'network_mode': network_name}
c.SwarmSpawner.remove_services = True
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or …
```

Swarmspawner to support new-style Docker Swarm mode

---

.travis.yml
dev-requirements.txt
dockerspawner/dockerspawner.py
dockerspawner/swarmspawner.py
dockerspawner/systemuserspawner.py
tests/conftest.py
tests/test_dockerspawner.py
tests/test_swarmspawner.py
tests/test_systemuserspawner.py
tests/volumes_test.py

This greatly reduces the complexity and duplication of the SwarmSpawner, which has config almost entirely shared with DockerSpawner.
Methods factored-out where the two differ:
- get_object (inspect_container|service)
- create_object (docker create, service create)
- start_object (docker start, no-op)
- stop_object (docker stop, no-op)
- remove_object (docker remove, service rm)
Additional fixes in SwarmSpawner:
- Fix ip/port resolution for exposed swarm ports
- Dedicated config for overriding Task/Endpoint/Container/Resources, rather than overloading `extra_create_kwargs`, which is by definition extra kwargs to be passed to create and only create.
Before merging this, I'll make sure there are basic tests for these Spawners running on Travis

SwarmSpawner inherits from DockerSpawner

---

README.md

Each spawner's hyperlinks didn't properly jump, could be due to a change in Markdown parsing; but all's resolved now. :smiley: 
Hyperlinks fixed: 
- DockerSpawner 
- SwarmSpawner 
- SystemUserSpawner

Fixing README's subsection links

---

dockerspawner/swarmspawner.py

[Hub docs](https://jupyterhub.readthedocs.io/en/stable/api/spawner.html#jupyterhub.spawner.Spawner.poll) say that poll should return None when the server is still starting.
DockerSpawner's poll function most likely needs to change as well, but I don't really understand how it's doing the status check, so I'm not going to touch it.

Return None on poll of "starting" container

---

dockerspawner/dockerspawner.py

this was the intended behavior
Only list, dict, and callable returning list or dict are valid
None is not a valid whitelist
closes https://github.com/jupyterhub/jupyterhub/issues/2318

default image_whitelist to empty dict

---

.travis.yml
dockerspawner/dockerspawner.py
tests/test_dockerspawner.py
tests/volumes_test.py

default: ifnotpresent
This removes the common requirement to pull the default image.
It is pulled by default on the first launch.
closes #121

add DockerSpawner.pull_policy

---

dockerspawner/dockerspawner.py
dockerspawner/swarmspawner.py
dockerspawner/volumenamingstrategy.py

Fixes #290 #291 
According to the parent class [Spawner](https://github.com/jupyterhub/jupyterhub/blob/7742bfdda5f466ed8f291c49bcb774a2bfad9c1e/jupyterhub/spawner.py#L766), the method template_namespace() should be a method.
So the template_namespace() method of the subclass DockerSpawner should also be a method, instead of a property (which caused the 'dict' object is not callable' error mentioned in #290 and #291). 
So I removed the `@property` decorator.

fix incompatible method template_namespace

---

dockerspawner/dockerspawner.py

This PR adds the ability to execute additional commands inside the container after starting it.
Useful for copying a notebook from a read_only volume mount somewhere like `/tmp/notebooks/` to home directory for temporary users to interact with a notebook unique for every user instead of mounting the notebook on a read-write volume.
My motivation for doing this is that I run JupyterHub server for a temporary amount of time to conduct a seminar or presentation in my lab where I want the students experiment around with the data. So there're no users created permanently. 
The server would run a bare minimum image with the needed packages then I mount the data on a read-only volume such as `/home/temp_user/Data/*` and the notebook will be copied to `/home/temp_user/notebook.ipynb`.
Edit: …

Added post_start_cmd

---

dockerspawner/systemuserspawner.py

Fixes issue jupyterhub/dockerspawner#299.
The home directory of the user on the host can be looked up via the
`pwd` database, which is useful when dealing with non-local users
(e.g., through LDAP authentication).
The lookup can be enabled by setting `host_homedir_format_string` to
an empty string or `None`.

Allow lookup of host homedir via `pwd`

---

dockerspawner/dockerspawner.py

For example, pull from my.docker.repo:8888/image:tag or my.docker.repo:8888/image is possible.
Closes #313

Fix issue with pulling images from custom repos that contain a port

---

dockerspawner/dockerspawner.py

As noted by @zeehio in [this comment](https://github.com/jupyterhub/dockerspawner/issues/257#issuecomment-492275806)
the default ``name_template`` is not compatible with using named servers. Should the default be updated?
The current docstring mentions backward compatibility. If
backward-compatibility of container names is very important, perhaps it would
be better to leave the default as is and simply mention ``{servername}`` in the
docstring and the README.

Make default name_template compatible with named servers.

---

dockerspawner/systemuserspawner.py

Thanks for your work.
The `SystemUserSpawner` allows to span a docker container with the `NB_UID` environment variable set, so files are created with the username we want (mapped from the system). However it does not pass the `NB_GID` variable, so the group ID is always fixed to 100 or to any other number.
This PR provides the `group_id` feature and passes it to `NB_GID` so the created single user notebooks know with which group ID files should be created.

SystemUserSpawner: Pass group id to the container

---

.travis.yml
RELEASE.md
dockerspawner/_version.py

Adds release instructions and a travis deploy job.
@consideRatio, do you think you can help with the `PYPI_PASSWORD` env var setup here too? :heart:

Add release instructions and Travis deploy

---

.travis.yml
dev-requirements.txt
tests/conftest.py
tests/test_dockerspawner.py
tests/test_swarmspawner.py
tests/test_systemuserspawner.py

- Updates the tests to work with latest JupyterHub versions: 1.0 and 1.1
- Use `pytest-asyncio` instead of `pytest-tornado`.
Note: `jupyterhub/singleuser:1.1` doesn't exist due to an issue with docker tags so the tests for JH 1.1 fail.

Test with latest jh

---

.travis.yml
dockerspawner/dockerspawner.py
tests/conftest.py
tests/test_dockerspawner.py
tests/test_swarmspawner.py
tests/test_systemuserspawner.py

we haven't made a release yet with #315 (merged last month), but the default template added there allows collisions between certain usernames and named servers because `-` is considered a safe character and not escaped.
This changes the default template to use `__`, the doubled escape character (same as on KubeSpawner, which uses `-` as the escape character), which cannot occur in an escaped username or servername.
This also ensures the escaped form of servername is used in the template, matching handling of usernames.
Additionally, this persists object_name in state, to avoid changes in the template (as is done here) from causing a disconnect between objects across configuration changes.
That is, changes in the template will only affect newly created objects, not ones that already exist. …

avoid name collisions when using named servers

---

dockerspawner/dockerspawner.py

This is commit b1ccf86 from #373 to avoid deviations from the mounts spec.
Adding support for optional things can be a separate discussion, but a case needs to be made to deviate from established specs.

Add mounts option for more advanced binds

---

dockerspawner/dockerspawner.py

Add support for the `auto_remove` option in `host_config`, to [enable auto-removal of the container on daemon side when the container’s process exits](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.create_host_config):
- Cover the case of the main process (pid 1) terminating itself, for example when using `--NotebookApp.shutdown_no_activity_timeout`
- Reuse the existing `remove` option

Add auto_remove to host_config

---

README.md

We had a TravisCI badge that we shouldn't have.

Add GitHub Action readme badge

---

dockerspawner/dockerspawner.py
dockerspawner/swarmspawner.py

skips unhelpful pull by default on swarm because the pull won't usually happen on the same node as the container anyway
closes #394

add 'skip' option for pull_policy

---

dockerspawner/dockerspawner.py
tests/test_dockerspawner.py
tests/volumes_test.py

While containers allow more characters, networking and the like are more strict.
To ensure things like DNS work (required for swarm, internal ssl), use a stricter DNS-safe subset for escaping.
c.DockerSpawner.escape is now a configurable and can be overridden to preserve old behavior and/or use other schemes.
closes #205
closes #326
closes #305
closes #342
closes #262
closes #209

Make escaping DNS-safe

---

dockerspawner/dockerspawner.py

instead of an observer, which isn't kind to subclasses
closes #317

Use default cmd=None to indicate using the image command

---

dockerspawner/swarmspawner.py

Error: SwarmSpawner, InvalidArgument: Incompatible options have been provided for the bind type mount.
Scenario: https://github.com/jupyterhub/dockerspawner/issues/263
I solved this issue, subclassing SwarmSpawner:
Creation of a module "modspawner.py"
`from dockerspawner import SwarmSpawner
class ModSwarmSpawner(SwarmSpawner):
@Property
def mount_driver_config(self):
if self.volume_driver:
return DriverConfig(
name=self.volume_driver, options=self.volume_driver_options or None
)
return None`
Add to JupyterHub settings:
`c.JupyterHub.spawner_class = 'modspawner.ModSwarmSpawner'`
The main reason is because of a improprely implementation of mount_driver_config method, of the SwarmSpawner Class.
This methods always returns a DriverConfig, even if no driver config was set.
When the spawner …

(PATCH) SwarmSpawner, InvalidArgument: Incompatible options have been provided for the bind type mount.

---

dockerspawner/systemuserspawner.py

when True, defer to image handing of $NB_UID and $NB_GID
this was previously a hard-to-opt-out default, but I think should be opt-in because images that do not support this will run all uses as root by default.
Downside of off-by-default: it's an extra flag needed to use docker-stacks to their full potential (they should still work without it, though, but usernames will not match, etc.)
Upside: userid is always right by default, no matter what image you use, no longer launch images as root that don't need it
closes #311
closes #283

add SystemUserSpawner.run_as_root

---

CHANGELOG.md
dockerspawner/_version.py
dockerspawner/dockerspawner.py
tests/test_deprecations.py

Highlights the breaking changes in run_as_root and container-name escaping.
Next version drops the leading 0, so planning to release 12.0 instead of 0.12.
closes #366

Changelog for 12.0

---

dockerspawner/dockerspawner.py
tests/test_dockerspawner.py

Similarly to the `allowed_images` setting, it would be very convenient to be able to set the `mem_limit` to a callable, to have more flexibility to enforce memory limits.
This feature would for instance allow easily define user-specific memory limits in `jupyterhub_config.py`:
```python
def per_user_mem_limit(spawner):
username = spawner.user.name
ram_limits = {}
try:
with open("/srv/jupyterhub/ram_limits.json") as f:
ram_limits = json.load(f)
except:
pass
return ram_limits.get(username, "32G")
c.SystemUserSpawner.mem_limit = per_user_mem_limit
```

Allow to specify a callable for `mem_limit`

---

dockerspawner/dockerspawner.py
tests/conftest.py
tests/test_dockerspawner.py

according to [the docs](https://docs.docker.com/config/containers/resource_constraints/#cpu) we need to specify cpu_quota in terms of cpu_period. The default period is 100ms
closes #428

support cpu limit via cpu_quota / cpu_period

---

.github/workflows/test.yml
docs/source/spawner-types.md
tests/test_dockerspawner.py

DockerSpawner more or less works with Podman, to the point where most of the DockerSpawner tests pass! Setting up Podman as a daemon (required for compatibility with Docker) has also gotten a lot easier so now it's just a single command.
Closes https://github.com/jupyterhub/dockerspawner/issues/360

Add Podman to docs

---

examples/internal-ssl/.env
examples/internal-ssl/Dockerfile
examples/internal-ssl/README.md
examples/internal-ssl/docker-compose.yml
examples/internal-ssl/jupyterhub_config.py

Has to mostly be a duplicate of the jupyterhub service, just to load the config.
This service runs to completion, to ensure the certificates are created
- proxy requires generate-certs to finish, which ensures the certs are available, otherwise proxy would crash
- hub requires proxy to be responsive, which should ensure proxy DNS is defined
removes DNS check from hub config, which should be redundant with the added healthy-proxy condition
I think this closes #445 which was caused by the hub and proxy needing to wait for each other:
- hub waits for proxy DNS to resolve, which is only true while proxy is running
- proxy crashes if certs don't exist, creating a race where the proxy container must exist (so that the hub can start), but not have tried to read the certs, else it will crash

add generate-certs service to internal-ssl example

---

dockerspawner/dockerspawner.py
tests/test_dockerspawner.py

otherwise, we'll persist object_name in state forever, rather than just when `remove=False`
closes #437

clear object_id when removing object

---

examples/swarm/Dockerfile
examples/swarm/docker-compose.yml

add newly required attachable arg to network (required in compose 3.2, apparently)
closes #452

update versions in swarm example

---

dockerspawner/dockerspawner.py

`imagename` is currently set to like `"binder-examples-conda:HEAD"`, and a colon `:` is problematic when used as a part of a docker volume name.
```python
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}--{imagename}': notebook_dir }
```
This PR sets `imagename` to be `"binder-examples-conda-HEAD"`, instead.

Fix imagename not to include letter ':'

---

tests/test_dockerspawner.py

- added new parameters to test allowed images passed as callables and lists. 
- mocked docker_host os environment to test that _default_host_ip correctly parses the url if the environment variable exists.

test callable allowed_images and host_ip

---

tests/test_dockerspawner.py

- set up allowed_images dictionary to test that image options are correctly displayed to user
- set up an image options formdata to test accurate conversion to user options
- added parameters of escape types to test validation of escape
- created DockerSpawner instance to test _legacy_escape on a container name
Reference: https://github.com/jupyterhub/outreachy/issues/39

test options_form and escape

---

.github/workflows/test.yml
dev-requirements.txt
pyproject.toml
tests/test_dockerspawner.py
tests/test_swarmspawner.py
tests/test_systemuserspawner.py

- removed matrix config for Python 3.6 since it reached [end of life](https://endoflife.date/python)
- added matrix config for Python 3.9 using JupyterHub 3.1.1
- added matrix config for Python 3.11 using JupyterHub 3.1.1
Reference #476

Add test strategy for JupyterHub v3.1.1

---

.github/dependabot.yaml

- Only merge after #486 so we can avoid PRs bumping things and merge conflicts

Add dependabot.yaml to bump github actions

---

dockerspawner/dockerspawner.py

This PR adds an example to the API reference for `extra_create_kwargs`.
Additionally, it fixes inline code formatting by adding an additional `` ` `` enclosing each end of the text. The existing usages involve single backticks ala Markdown, whereas [double backticks are used in RST](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#inline-markup).
Continued from #492 
cc @manics

Add extra_create_kwargs example, plus docs readability improvements

---

dockerspawner/dockerspawner.py

When several images allowed in dockerspawner and template_name is containing {imagename}, it would be expected that the selected image name is used within the object_name. I didn't found a way to do it as object_name is using default image name if not specified.
This fix updates object_name at container start after check_allowed image. It is working at least for the above use case, don't know if it is the best way to do it and if it has other consequences elsewhere. Also, I set the method _object_name_for_current_image as an async method but I am not very familiar with that method type, so here also I am not sure it is needed.
Hopping it can help, many thanks for that package anyway.

update object_name with current image

---

dockerspawner/dockerspawner.py
docs/source/docker-image.md
examples/internal-ssl/.env
tests/conftest.py

Bump up a couple other versions in the Dockerfile examples as well.
Ref https://github.com/jupyterhub/team-compass/issues/688

Switch default image to quay.io

---

dockerspawner/dockerspawner.py

for e.g. per-user device requests
closes #473
Removes long-deprecated kwargs from `.start()` which no longer work with the callables.

allow extra_host_config and extra_create_kwargs to be callable

---

dockerspawner/dockerspawner.py

avoids clobbering. Closes #465 
includes #500 to avoid conflict since it touches some of the same lines

Merge host config/create_kwargs

---

dockerspawner/dockerspawner.py

replace pformat/pprint with json.dumps, so that the polled container status in log will be printed in a single line, which is friendly for logger collector and parser.

compact debug log into single line

---

dockerspawner/dockerspawner.py
tests/test_dockerspawner.py

Closes #524.
I believe similar changes should also be done to other spawners; didn't check those yet.

Convert options_from_form into traitlet

---

.github/workflows/test.yaml
README.md
dev-requirements.txt
pyproject.toml
requirements.txt
setup.py
tests/conftest.py

increase lower bound on pytest-asyncio to 0.24
this may create a problem for the older jupyterhub tests due to imported fixtures, but let's see...

require Python 3.9, jupyterhub 4, unpin pytest-asyncio

---

dockerspawner/systemuserspawner.py
docs/source/changelog.md

and update a versionadded since this is a major revision due to the dependency bump
trying to bring this repo back to health with a fresh release

changelog for 14.0

---

dockerspawner/dockerspawner.py

- Don't require specific keys (like 'source') to be present, as there are mount types that don't need that (like https://docs.docker.com/engine/storage/tmpfs/)
- Format all values, not just source and destination.
- Remove two layers of indirection - mount_binds was only used in one place, so let's just use it there.

Cleanup how mounts are handled
