jupyterhub/dockerspawner

singleuser/singleuser.sh
systemuser/systemuser.sh

Makes the SIGTERM sent by `docker stop` hit the correct process.

DEV: Use exec for shell entrypoints.

---

dockerspawner/dockerspawner.py

Fixes https://github.com/jupyter/dockerspawner/issues/19

DEV: Use `inspect_container` instead of parsing `containers`.

---

dockerspawner/dockerspawner.py

I'm not 100% sure container_ip is always the right value for this, but I think it is.

specify container ip on user.server

---

dockerspawner/dockerspawner.py

Add version='auto' to the docker client to connect to server API versions other than the latest.

Docker client auto version

---

dockerspawner/dockerspawner.py

- config=True, help at the top-level
- add None to Enum

fix traitlets usage on tls_assert_hostname

---

dockerspawner/dockerspawner.py

@richafrank `create_host_config` was giving me a deprecation warning

Fix docker deprecation warning

---

singleuser/Dockerfile
singleuser/singleuser.sh
systemuser/Dockerfile
systemuser/systemuser.sh

which took away permission to write the single-user script file
closes #60
closes #59

handle changes in upstream docker images

---

systemuser/Dockerfile
systemuser/systemuser.sh

Typo in Dockerfile and need to explicitly set the PATH.

Fix systemuser container

---

.travis.yml
dockerspawner/dockerspawner.py

and a little pyflakes check while we don't have any real Python tests.

test docker builds on Travis

---

dockerspawner/dockerspawner.py
dockerspawner/systemuserspawner.py

I made the user directory mapping a bit more flexible in order to support some configurations our group runs.

Added flexibility for directory mapping inside containers.

---

dockerspawner/dockerspawner.py

Added Docker container linking so that the user-container gets linked to the jupyterhub container, which makes communication much easier.

Added Docker container linking

---

dockerspawner/dockerspawner.py

allows specifying arbitrary links for containers
follow-up of #69

passthrough links directly

---

dockerspawner/dockerspawner.py
requirements.txt

self.env is incomplete
closes #71

use 0.4 get_env() for single-user env

---

systemuser/Dockerfile

it confuses things
Related to #80

remove jovyan user from systemuser image

---

dockerspawner/dockerspawner.py

To get the spawner environment

Extend get_env instead of `_env_default`

---

tools/rebase-singleuser

builds singleuser image with a specified FROM target
closes #82
cf jupyter/docker-stacks#162

add rebase-singleuser script

---

.travis.yml
README.md
dockerspawner/dockerspawner.py
dockerspawner/systemuserspawner.py
examples/oauth/README.md
singleuser/Dockerfile
singleuser/README.md
systemuser/Dockerfile
systemuser/README.md

update jupyterhub urls

---

examples/oauth/README.md
examples/oauth/env

Add caution about keeping secrets private

---

dockerspawner/dockerspawner.py

remove unused itertools import

---

singleuser/Dockerfile

I'm planning to move it soon, so this will stop working

pin singleuser script to 0.6.1 in docker images

---

requirements.txt

remove jupyter_client from requirements

---

README.md

So that it's in a more discoverable place rather than buried deep within #54 😄

Add section to README on docker swarm

---

CHANGELOG.md

Add links to compare releases and add release dates. Similar to https://github.com/jupyterhub/jupyterhub/pull/711

Add links to compare GitHub releases to changelog

---

singleuser/README.md

Added clarification based on Gitter discussion.
@akhmerov @minrk

Add clarification on persistence as suggested by @akhmerov

---

dockerspawner/dockerspawner.py

Also set env variables to support memory discoverability with
https://github.com/jupyterhub/jupyterhub/issues/854

Add ability to set memory limit for containers explicitly

---

CHANGELOG.md

cc @willingc
I released JupyterHub 0.7.1 with the `will_resume` fix, and I'd like to ship this one today or tomorrow, as well.

changelog for 0.6

---

dockerspawner/dockerspawner.py

mem_limit has been moved to host_config in API version 1.19

move mem_limit config to host_config

---

CHANGELOG.md

in preparation for release
cc @JamiesHQ

Changelog for 0.7

---

setup.py

avoids different distutils/setuptools behavior

install with setuptools

---

dockerspawner/dockerspawner.py
singleuser/Dockerfile

always, rather than during stop
closes jupyterhub/jupyterhub#1202

set will_resume to `not remove_containers`

---

dockerspawner/dockerspawner.py

make docker client configurable

---

CHANGELOG.md

changelog for 0.8

---

dockerspawner/dockerspawner.py

Instead of relying on custom environment variables that images have to handle, pass existing env/argv inherited from Spawner. This allows more images to more easily be used with DockerSpawner, since they don't need to specify any handling of special environment variables set only by DockerSpawner. Instead, they only need to have jupyterhub installed and launch `jupyterhub-singleuser` as their CMD. If the images don't launch singleuser,
`c.Spawner.cmd` config is respected and can be used.
- Spawner.cmd config is now respected
- Spawner.get_args() behavior is now respected,
and the default is to extend the image's own CMD.
Spawner.cmd overrides the image CMD.
Several duplicate/inaccurately named arguments are deprecated, as well:
- .container_port is replaced with the existing .port, which …

respect upstream env, args, ip, port

---

CHANGELOG.md
README.md

it would be nice to get this out because it improves default compatibility with JupyterHub 0.8.

changelog for 0.9

---

dockerspawner/dockerspawner.py

Allow host_ip to be configurable

---

CHANGELOG.md

Mainly the addition of SwarmSpawner

changelog for 0.10

---

dockerspawner/swarmspawner.py

I was having the same question as #264 
Added placement as a config option, so that this works:
`c.SwarmSpawner.extra_placement_spec = { 'constraints' : ['node.role==worker'] }`

docker service placement constraints as config option

---

examples/simple/Dockerfile
examples/simple/README.md
examples/simple/jupyterhub_config.py
examples/simple/requirements.txt

shows the basics of networking to get started
cc @cnydw who brought up some questions on gitter

add simple example

---

setup.py

so users can do:
c.JupyterHub.spawner_class = 'docker'

register entrypoints for jupyterhub 1.0

---

dockerspawner/swarmspawner.py

Spawner.start should only return when a server process is expected to be running.
Service creation can return long before this. Use start_object to wait for the service to be running.
cc @jaredvacanti who I believe is running into this right now.

wait for service to be running before returning from start

---

.travis.yml
dev-requirements.txt
dockerspawner/dockerspawner.py
dockerspawner/swarmspawner.py
dockerspawner/volumenamingstrategy.py
examples/internal-ssl/.env
examples/internal-ssl/Dockerfile
examples/internal-ssl/README.md
examples/internal-ssl/docker-compose.yml
examples/internal-ssl/jupyterhub_config.py
examples/internal-ssl/test_internal_ssl.py
tests/volumes_test.py

testing https://github.com/jupyterhub/jupyterhub/pull/2055
defines .move_certs using docker put_archive to create a volume

implement internal-ssl support

---

dockerspawner/swarmspawner.py

Fixes #298 
Added NEW, ASSIGNED and ACCEPTED states, according to docker's [documentation](https://docs.docker.com/engine/swarm/how-swarm-mode-works/swarm-task-states/)

add more swarm task states

---

dockerspawner/dockerspawner.py

Analogous to https://github.com/jupyterhub/kubespawner/pull/193
Thanks @yuvipanda for guidance.

Add JUPYTER_IMAGE_SPEC to env.

---

docs/source/docker-image.md

Really nice work on the docs!
Spotted a minor typo while going through them.

Typo fix in the docs

---

dockerspawner/dockerspawner.py
tests/test_deprecations.py
tests/test_dockerspawner.py

cf https://github.com/jupyterhub/team-compass/issues/299
https://github.com/jupyterhub/jupyterhub/pull/3090

Rename DockerSpawner.whitelist to allowed

---

dockerspawner/swarmspawner.py

Occasionally single-user task is not created immediately when `create_service` call yields in the `create_object()` method. Therefore, it is necessary to wait until it is created. Wait loop added to the end of `create_object()` method guarantees this. This problem is linked to [Issue 330](https://github.com/jupyterhub/dockerspawner/issues/330) and I think the update solves the last unsolved (e.g. "we are still seeing") part, which seems to occur more frequently if swarm includes nodes with different architectures (e.g. Arm64v8 and AMD64) (it is also my case).
The change also includes the patch by @gdbassett [mentioned in Issue 330](https://github.com/jupyterhub/dockerspawner/issues/330#issuecomment-525489513) to property get the task created by the service and check its states. `ready` …

Make sure that create_object() creates the service task

---

examples/simple/Dockerfile
examples/simple/jupyterhub_config.py

- bump versions
- use entrypoints for selecting auth, spawner

touch up simple example

---

docs/source/docker-image.md

so exact copy/paste results in more recent results
and add a note that you should pick the right version
closes #403

update versions in docker-image docs

---

dockerspawner/dockerspawner.py

allows template formatting in any key, value, or list item in passthrough
config
Finishes up #368
closes #367
closes #166

apply template formatting to all of extra_create_kwargs, extra_host_config

---

examples/internal-ssl/.env
examples/internal-ssl/Dockerfile
examples/internal-ssl/docker-compose.yml
examples/internal-ssl/jupyterhub_config.py
examples/internal-ssl/test_internal_ssl.py

seems to be failing. not sure why.

bump requirements in internal-ssl example

---

examples/swarm/Dockerfile
examples/swarm/README.md
examples/swarm/docker-compose.yml
examples/swarm/jupyterhub_config.py

with latest images, etc.
Removes some example commands that might be copied and run if not reading carefully enough.
Tested and confirmed it works as-is (docker-for-mac, 19.03.12)
closes #376

Update swarm example

---

dockerspawner/dockerspawner.py
tests/test_dockerspawner.py

for debugging errors
stderr at warning-level, stdout at debug-level
with special handling of likely "OCI runtime exec failed" message, which docker puts on stdout but is clearly an error
closes #422

Log post_start exec output

---

dev-requirements.txt
tests/conftest.py

more debug info from docker when tests fail

---

README.md
RELEASE.md
docs/source/contributing.md
docs/source/spawner-types.md

update release steps for main branch

---

.github/workflows/test.yml
tests/conftest.py

Needs a 2.0.0rc4 tag in https://hub.docker.com/r/jupyterhub/singleuser/tags to (hopefully) pass

Test jupyterhub2

---

.readthedocs.yml

should get docs building again

Use python 3.11 on RTD

---

dockerspawner/dockerspawner.py

Deprecated since JupyterHub 0.8 (2017), the CLI arg it specified has stopped working in JupyterHub 4 with the singleuser extension, which lacks its own Hub-specific CLI args.
Leave warning in place, but louder now, and _ignore_ the argument since it has stopped working with JupyterHub 4.
cf https://github.com/jupyter/docker-stacks/issues/1993

Remove deprecated, broken hub_ip_connect

---

docs/source/changelog.md

Changelog for 13

---

dev-requirements.txt

temporary pin for pytest-asyncio

---

dockerspawner/dockerspawner.py
dockerspawner/systemuserspawner.py
tests/volumes_test.py

finally picks up #494 to get ready to merge
minor changes, only to set propagation if specifed, avoiding compatibility problems

support for bind propagation

---

dev-requirements.txt
tests/conftest.py

- remove unmaintained netifaces in favor of equivalent functionality in psutil
- remove unused outdated notebook pin

update some test dependencies
